#pragma once

#include <merak/tool_meta.hpp>
#include <string_view>

namespace merak::tools {

inline const ToolMeta TOOL_CATALOG[] = {
    // ==============================
    // Pinned (8)
    // ==============================

    {
        .name = "read_file",
        .description = "Read file contents with optional line range and outline mode",
        .triggers = {"read", "view", "show", "inspect", "open", "cat", "查看", "读取", "打开", "看看"},
        .pinned = true,
        .intents = {IntentType::CodeRead},
        .scope = Scope::Local,
        .requires_caps = {},
        .schema_tokens = 35,
    },
    {
        .name = "write_file",
        .description = "Create or overwrite a file",
        .triggers = {"write", "create file", "save", "output", "new file", "创建文件", "写入", "保存"},
        .pinned = true,
        .intents = {IntentType::CodeEdit},
        .scope = Scope::Local,
        .requires_caps = {},
        .schema_tokens = 25,
    },
    {
        .name = "str_replace",
        .description = "Replace text in files with exact string matching",
        .triggers = {"replace", "edit", "modify", "update", "fix", "refactor", "替换", "修改", "编辑"},
        .pinned = true,
        .intents = {IntentType::CodeEdit},
        .scope = Scope::Local,
        .requires_caps = {},
        .schema_tokens = 40,
    },
    {
        .name = "list_dir",
        .description = "List directory structure and files",
        .triggers = {"list directory", "directory", "files", "tree", "dir", "目录", "文件列表", "文件夹"},
        .pinned = true,
        .intents = {IntentType::CodeRead},
        .scope = Scope::Local,
        .requires_caps = {},
        .schema_tokens = 25,
    },
    {
        .name = "grep",
        .description = "Search file contents with regex patterns",
        .triggers = {"grep", "regex", "find in files", "text search", "搜索代码", "代码搜索", "全文搜索"},
        .pinned = true,
        .intents = {IntentType::CodeRead},
        .scope = Scope::Local,
        .requires_caps = {},
        .schema_tokens = 40,
    },
    {
        .name = "glob",
        .description = "Find files by name pattern",
        .triggers = {"find files", "glob", "locate", "file pattern", "找文件", "文件名", "定位文件"},
        .pinned = true,
        .intents = {IntentType::CodeRead},
        .scope = Scope::Local,
        .requires_caps = {},
        .schema_tokens = 25,
    },
    {
        .name = "execute_bash",
        .description = "Execute shell commands for builds, tests, installs, git, CLI tasks",
        .triggers = {"run", "execute", "build", "test", "install", "command", "shell", "运行", "执行", "编译", "测试"},
        .pinned = true,
        .intents = {IntentType::CodeEdit, IntentType::CodeRead, IntentType::Git},
        .scope = Scope::Local,
        .requires_caps = {},
        .schema_tokens = 35,
    },
    {
        .name = "tool_search",
        .description = "Search and activate deferred tools. Use select:NAME to get full schema.",
        .triggers = {"tool_search", "find tool", "which tool", "available tools", "搜工具", "查工具"},
        .pinned = true,
        .intents = {IntentType::CodeRead},
        .scope = Scope::Local,
        .requires_caps = {},
        .schema_tokens = 25,
    },

    // ==============================
    // Deferred Platform (12)
    // ==============================

    {
        .name = "git",
        .description = "Git operations: status, diff, log, show, blame, file_history, log_search, contributors, commit, revert_commit, stash",
        .triggers = {"git", "commit", "diff", "blame", "file_history", "log", "status", "branch", "stash", "提交", "版本", "差异", "日志"},
        .pinned = false,
        .intents = {IntentType::Git},
        .scope = Scope::LocalGit,
        .requires_caps = {},
        .schema_tokens = 50,
    },
    {
        .name = "web_fetch",
        .description = "Fetch URL content — web pages, APIs, documentation",
        .triggers = {"fetch", "url", "web", "http", "download", "api call", "curl", "网页", "网址", "获取网页", "访问链接"},
        .pinned = false,
        .intents = {IntentType::Network},
        .scope = Scope::External,
        .requires_caps = {},
        .schema_tokens = 25,
    },
    {
        .name = "web_search",
        .description = "Search the web across multiple engines",
        .triggers = {"web search", "search web", "search online", "google", "网络搜索", "在线搜索", "搜索网络"},
        .pinned = false,
        .intents = {IntentType::Network},
        .scope = Scope::External,
        .requires_caps = {},
        .schema_tokens = 25,
    },
    {
        .name = "lsp",
        .description = "Language Server Protocol: go_to_definition, find_references, hover, rename, code_action, diagnostics, formatting",
        .triggers = {"lsp", "language server", "definition", "references", "hover", "rename", "diagnostics", "定义", "引用", "重命名", "诊断"},
        .pinned = false,
        .intents = {IntentType::CodeIntel},
        .scope = Scope::Local,
        .requires_caps = {Capability::LSPServer},
        .schema_tokens = 90,
    },
    {
        .name = "symbols",
        .description = "Extract function/class/struct signatures from a file using tree-sitter",
        .triggers = {"symbols", "functions", "classes", "signatures", "outline", "符号", "函数列表", "类列表"},
        .pinned = false,
        .intents = {IntentType::CodeIntel},
        .scope = Scope::Local,
        .requires_caps = {},
        .schema_tokens = 25,
    },
    {
        .name = "memory",
        .description = "Memory operations: store, retrieve, forget, feedback, search, profile",
        .triggers = {"memory", "remember", "recall", "forget", "store", "retrieve", "记忆", "记住", "回忆", "存储"},
        .pinned = false,
        .intents = {IntentType::Memory},
        .scope = Scope::CrossSession,
        .requires_caps = {Capability::MemoryService},
        .schema_tokens = 40,
    },
    {
        .name = "session",
        .description = "Session lifecycle: compact, rollback, config, history, summary, timeline",
        .triggers = {"compact", "rollback", "config", "adjust", "压缩", "回滚", "配置", "历史"},
        .pinned = false,
        .intents = {IntentType::Introspect},
        .scope = Scope::Local,
        .requires_caps = {},
        .schema_tokens = 60,
    },
    {
        .name = "agent",
        .description = "Multi-agent: spawn (create sub-agent), get_result, send_message, list",
        .triggers = {"agent", "spawn", "orchestrate", "sub-agent", "代理", "子代理"},
        .pinned = false,
        .intents = {IntentType::AgentOp},
        .scope = Scope::External,
        .requires_caps = {Capability::AgentSpawner},
        .schema_tokens = 40,
    },
    {
        .name = "task",
        .description = "Durable task list: create, update, list, complete, archive",
        .triggers = {"task", "todo", "checklist", "track", "任务", "待办", "追踪"},
        .pinned = false,
        .intents = {IntentType::TaskMgmt},
        .scope = Scope::CrossSession,
        .requires_caps = {},
        .schema_tokens = 30,
    },
    {
        .name = "ask_user",
        .description = "Ask the user interactive questions for clarification or confirmation",
        .triggers = {"ask", "question", "confirm", "clarify", "提问", "确认", "询问"},
        .pinned = false,
        .intents = {IntentType::Introspect},
        .scope = Scope::Local,
        .requires_caps = {},
        .schema_tokens = 20,
    },
    {
        .name = "enter_plan_mode",
        .description = "Enter plan-authoring mode. Write operations restricted while planning.",
        .triggers = {"plan", "enter plan mode", "计划模式"},
        .pinned = false,
        .intents = {IntentType::Introspect},
        .scope = Scope::Local,
        .requires_caps = {Capability::PlanLifecycle},
        .schema_tokens = 15,
    },
    {
        .name = "exit_plan_mode",
        .description = "Submit the authored plan for user review and exit plan-authoring mode.",
        .triggers = {"exit plan", "submit plan", "退出计划"},
        .pinned = false,
        .intents = {IntentType::Introspect},
        .scope = Scope::Local,
        .requires_caps = {Capability::PlanLifecycle},
        .schema_tokens = 20,
    },

    // ==============================
    // Worldbuilding (19)
    // ==============================

    {
        .name = "describe_character",
        .description = "Get detailed character profile by name",
        .triggers = {"角色", "character", "描述", "describe", "profile", "查看角色", "人物"},
        .pinned = false,
        .intents = {IntentType::DomainRead},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "search_my_diary",
        .description = "Search the character's personal diary entries",
        .triggers = {"日记", "diary", "搜索日记", "个人记录", "journal"},
        .pinned = false,
        .intents = {IntentType::DomainRead},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "look_around",
        .description = "Observe the current scene and environment",
        .triggers = {"观察", "look", "场景", "scene", "周围", "查看周围", "环顾"},
        .pinned = false,
        .intents = {IntentType::DomainRead},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "query_map",
        .description = "Query the world map for locations and regions",
        .triggers = {"地图", "map", "位置", "location", "区域", "region", "查询地图"},
        .pinned = false,
        .intents = {IntentType::DomainRead},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "query_history",
        .description = "Query world history: events, timelines, eras",
        .triggers = {"历史", "history", "事件", "event", "年代", "era", "查询历史"},
        .pinned = false,
        .intents = {IntentType::DomainRead},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "query_magic",
        .description = "Query the magic system: rules, spells, elements",
        .triggers = {"魔法", "magic", "咒语", "spell", "元素", "element", "查询魔法"},
        .pinned = false,
        .intents = {IntentType::DomainRead},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "query_faction",
        .description = "Query faction information: members, goals, alliances",
        .triggers = {"势力", "faction", "组织", "organization", "阵营", "查询势力"},
        .pinned = false,
        .intents = {IntentType::DomainRead},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "read_character_card",
        .description = "Read the full character card including hidden traits",
        .triggers = {"角色卡", "character card", "人物卡", "人物详情", "查看角色卡"},
        .pinned = false,
        .intents = {IntentType::DomainRead},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "read_secret",
        .description = "Read a secret's full content and revelation state",
        .triggers = {"秘密", "secret", "机密", "读取秘密", "查看秘密"},
        .pinned = false,
        .intents = {IntentType::DomainRead},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "read_foreshadowing",
        .description = "Read a foreshadowing entry: setup, payoff, status",
        .triggers = {"伏笔", "foreshadowing", "predict", "查看伏笔"},
        .pinned = false,
        .intents = {IntentType::DomainRead},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "list_open_foreshadowing",
        .description = "List all unpaid foreshadowing entries",
        .triggers = {"未回收伏笔", "open foreshadowing", "进行中伏笔", "伏笔列表"},
        .pinned = false,
        .intents = {IntentType::DomainRead},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "search_agent",
        .description = "Search for agents (characters, managers, gods) by name or role",
        .triggers = {"搜索角色", "search agent", "查找角色", "agent search", "角色搜索"},
        .pinned = false,
        .intents = {IntentType::DomainRead},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "query_world",
        .description = "General world query across all worldbuilding stores",
        .triggers = {"查询世界", "query world", "世界观", "world", "设定查询", "世界观查询"},
        .pinned = false,
        .intents = {IntentType::DomainRead},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "advance_world_time",
        .description = "Advance world time by a specified duration",
        .triggers = {"推进时间", "advance time", "时间推进", "跳过时间", "skip time"},
        .pinned = false,
        .intents = {IntentType::DomainWrite},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "create_character",
        .description = "Create a new character with name, role, and background",
        .triggers = {"创建角色", "create character", "新角色", "new character", "添加角色"},
        .pinned = false,
        .intents = {IntentType::DomainWrite},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "plant_foreshadowing",
        .description = "Plant a new foreshadowing entry with setup and planned payoff",
        .triggers = {"埋下伏笔", "plant foreshadowing", "设置伏笔", "铺垫", "埋伏笔"},
        .pinned = false,
        .intents = {IntentType::DomainWrite},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "expose_secret",
        .description = "Expose a secret to specified characters",
        .triggers = {"揭露秘密", "expose secret", "揭示秘密", "reveal secret", "透露"},
        .pinned = false,
        .intents = {IntentType::DomainWrite},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "end_scene",
        .description = "End the current scene and finalize narrative",
        .triggers = {"结束场景", "end scene", "场景结束", "finish scene", "收尾"},
        .pinned = false,
        .intents = {IntentType::DomainWrite},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
    {
        .name = "update_agent_prompt",
        .description = "Update an agent's system prompt at runtime",
        .triggers = {"更新提示", "update prompt", "修改提示词", "调整角色"},
        .pinned = false,
        .intents = {IntentType::DomainWrite},
        .scope = Scope::Local,
        .requires_caps = {Capability::Worldbuilding},
        .schema_tokens = 25,
    },
};

/// Returns true if `name` matches a pinned tool.
inline bool is_pinned(std::string_view name) {
    for (const auto& meta : TOOL_CATALOG) {
        if (meta.pinned && meta.name == name) return true;
    }
    return false;
}

/// Find a ToolMeta by name, returns nullptr if not found.
inline const ToolMeta* find_meta(std::string_view name) {
    for (const auto& meta : TOOL_CATALOG) {
        if (meta.name == name) return &meta;
    }
    return nullptr;
}

} // namespace merak::tools
